Repository Mr-Mappie/mappie, pull requests merged in 2024-10, with the labels that each got.

#108 Removed deprecated method 'parameter(String)'
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/ExplicitClassMappingCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/util/Identifiers.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/ConstructorParameterNotAFieldTest.kt
  mappie-api/src/commonMain/kotlin/tech/mappie/api/ObjectMappingConstructors.kt
  website/src/changelog.md
Labels: hacktoberfest-accepted

#114 Migrated compatibility tests to gradle-plugin
  .github/workflows/compatibility-test.yml
  .gitignore
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/ShouldTransformCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/ClassMappingRequestBuilder.kt
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/sources/ClassMappingSource.kt
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/sources/ImplicitClassMappingSourcesCollector.kt
  gradle-plugin/build.gradle.kts
  gradle-plugin/src/main/kotlin/tech/mappie/MappieGradlePlugin.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/IntegrationTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/TestBase.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/java/JavaClassWithConstructorCompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/java/JavaClassWithNonNullFieldCompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/java/JavaClassWithoutConstructorCompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/Kotlin1924CompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/Kotlin200CompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/Kotlin2020CompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/Kotlin2021CompatibilityTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/KotlinCompatibilityTestBase.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/kotlin/KotlinVersionSanityTest.kt
  test/java/.gitignore
  test/java/build.gradle.kts
  test/java/gradle/gradle-daemon-jvm.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle.kts
  test/kotlin-1.9.24/.gitignore
  test/kotlin-1.9.24/build.gradle.kts
  test/kotlin-1.9.24/gradle/gradle-daemon-jvm.properties
  test/kotlin-1.9.24/gradle/wrapper/gradle-wrapper.jar
  test/kotlin-1.9.24/gradle/wrapper/gradle-wrapper.properties
  test/kotlin-1.9.24/gradlew
  test/kotlin-1.9.24/gradlew.bat
  test/kotlin-1.9.24/settings.gradle.kts
  test/kotlin-2.0.0/.gitignore
  test/kotlin-2.0.0/build.gradle.kts
  test/kotlin-2.0.0/gradle/gradle-daemon-jvm.properties
  test/kotlin-2.0.0/gradle/wrapper/gradle-wrapper.jar
  test/kotlin-2.0.0/gradle/wrapper/gradle-wrapper.properties
  test/kotlin-2.0.0/gradlew
  test/kotlin-2.0.0/gradlew.bat
  test/kotlin-2.0.0/settings.gradle.kts
  test/kotlin-2.0.20/.gitignore
  test/kotlin-2.0.20/build.gradle.kts
  test/kotlin-2.0.20/gradle/gradle-daemon-jvm.properties
  test/kotlin-2.0.20/gradle/wrapper/gradle-wrapper.jar
  test/kotlin-2.0.20/gradle/wrapper/gradle-wrapper.properties
  test/kotlin-2.0.20/gradlew
  test/kotlin-2.0.20/gradlew.bat
  test/kotlin-2.0.20/settings.gradle.kts
  test/src/main/kotlin/EnumMapping.kt
  test/src/main/kotlin/GeneratedClassMapper.kt
  test/src/main/kotlin/GeneratedEnumMapper.kt
  test/src/main/kotlin/ObjectMapper.kt
  test/src/test/kotlin/EnumMapperTest.kt
  test/src/test/kotlin/NestedGeneratedClassMapperTest.kt
  test/src/test/kotlin/NestedGeneratedEnumMapperTest.kt
  test/src/test/kotlin/ObjectMapperTest.kt
Labels: testing

#115 Dependabot/npm and yarn/website/npm bdd6c2fa37
  website/.eleventy.js
  website/package-lock.json
  website/package.json
  website/src/_includes/partials/search-modal.html
Labels: documentation

#118 #62 added local configuration options
  compiler-plugin/src/main/kotlin/tech/mappie/MappieCompilerPluginRegistrar.kt
  compiler-plugin/src/main/kotlin/tech/mappie/MappieIrRegistrar.kt
  compiler-plugin/src/main/kotlin/tech/mappie/MappiePluginContext.kt
  compiler-plugin/src/main/kotlin/tech/mappie/config/MappieConfiguration.kt
  compiler-plugin/src/main/kotlin/tech/mappie/config/options/StrictEnums.kt
  compiler-plugin/src/main/kotlin/tech/mappie/config/options/StrictVisibility.kt
  compiler-plugin/src/main/kotlin/tech/mappie/config/options/UseDefaultArguments.kt
  compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/ClassMappingRequestBuilder.kt
  compiler-plugin/src/main/kotlin/tech/mappie/util/Identifiers.kt
  compiler-plugin/src/main/kotlin/tech/mappie/validation/MappingValidation.kt
  compiler-plugin/src/main/kotlin/tech/mappie/validation/problems/classes/ClassConfigProblems.kt
  compiler-plugin/src/main/kotlin/tech/mappie/validation/problems/classes/VisibilityProblems.kt
  compiler-plugin/src/main/kotlin/tech/mappie/validation/problems/enums/AllSourcesMappedProblems.kt
  compiler-plugin/src/main/kotlin/tech/mappie/validation/problems/enums/EnumConfigProblems.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/enums/EnumMapperWrongConfigTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/enums/EnumToEnumWithFewerEntriesTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/DefaultValueTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/ObjectMapperWrongConfigTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/configuration/UseDefaultArgumentsTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/configuration/strictness/EnumStrictnessTest.kt
  gradle-plugin/src/test/kotlin/tech/mappie/testing/configuration/strictness/VisibilityStrictnessTest.kt
  mappie-api/src/commonMain/kotlin/tech/mappie/api/config/MappieOptions.kt
  website/src/changelog.md
  website/src/posts/enum-mapping/posts/configuration.md
  website/src/posts/getting-started/posts/configuration.md
  website/src/posts/object-mapping/posts/configuration.md
Labels: enhancement

#119 Added build.gradle(.kts) language tabs to documentation
  website/src/_data/global.js
  website/src/_includes/layouts/base.html
  website/src/css/main.css
  website/src/js/prism.js
  website/src/js/tabs.js
  website/src/posts/enum-mapping/posts/configuration.md
  website/src/posts/getting-started/posts/installation.md
  website/src/posts/object-mapping/posts/built-in.md
  website/src/posts/object-mapping/posts/configuration.md
Labels: documentation
