Repository Mr-Mappie/mappie, pull requests merged in 2025-09, with the labels that each got.

#257 Fixed check of runtime usage of of mapping DSL for multiple object ma…
  compiler-plugin/src/main/kotlin/tech/mappie/fir/analysis/CompileTimeDslReceiverChecker.kt
  compiler-plugin/src/main/kotlin/tech/mappie/fir/analysis/ToCallChecker.kt
  compiler-plugin/src/main/kotlin/tech/mappie/util/Identifiers.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/FromValueTest.kt
  website/src/changelog.md
Labels: bug

#259 add test for compatibility with gradle 9.1
  gradle-plugin/src/test/kotlin/tech/mappie/testing/compatibility/gradle/Gradle91CompatibilityTest.kt
Labels: testing

#261 report all problems when having multiple complex inner objects
  compiler-plugin/src/main/kotlin/tech/mappie/ir/analysis/problems/classes/MapperGenerationRequestProblems.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/GeneratedClassFailMultipleTest.kt
Labels: bug

#260 improved performance of merge() utils
  compiler-plugin/src/main/kotlin/tech/mappie/util/MapExtensions.kt
Labels: enhancement

#265 Allow mapping to be used anywhere in a map function
  compiler-plugin/src/main/kotlin/tech/mappie/MappiePluginContext.kt
  compiler-plugin/src/main/kotlin/tech/mappie/fir/MappieAdditionalCheckersExtension.kt
  compiler-plugin/src/main/kotlin/tech/mappie/fir/analysis/FunctionBodyChecker.kt
  compiler-plugin/src/main/kotlin/tech/mappie/fir/analysis/MappieErrors.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/generation/MappieCodeGenerator.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/generation/classes/ObjectMappieCodeGenerator.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/generation/enums/EnumMappieCodeGenerator.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/reporting/PrettyPrinter.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/MappingFinder.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/MappingRequestResolver.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/ShouldTransformCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/classes/ClassMappingStatementCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/classes/ClassResolver.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/enums/EnumMappingBodyCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/enums/EnumMappingStatementCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/resolving/enums/EnumResolver.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/bodies/ExpressionsTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/bodies/InlineClassTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/bodies/ScopeFunctionsTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/bodies/StatementsTest.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/enums/ObjectMappieInsteadOfEnumMappieTest.kt
  website/src/changelog.md
Labels: enhancement

#278 Fixed #262
  compiler-plugin/src/main/kotlin/tech/mappie/ir/preprocessing/DefinitionsCollector.kt
  compiler-plugin/src/main/kotlin/tech/mappie/ir/util/Ir.kt
  compiler-plugin/src/test/kotlin/tech/mappie/testing/MapperInheritanceTest.kt
  website/src/changelog.md
Labels: bug
